# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/gsc/zynq7000/projects/hardware_design/zed_dma/zed_dma.srcs/sources_1/bd/dma/ip/dma_xbar_0/dma_xbar_0.xci
# IP: The module: 'dma_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/gsc/zynq7000/projects/hardware_design/zed_dma/zed_dma.srcs/sources_1/bd/dma/ip/dma_xbar_0/dma_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/gsc/zynq7000/projects/hardware_design/zed_dma/zed_dma.srcs/sources_1/bd/dma/ip/dma_xbar_0/dma_xbar_0.xci
# IP: The module: 'dma_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/gsc/zynq7000/projects/hardware_design/zed_dma/zed_dma.srcs/sources_1/bd/dma/ip/dma_xbar_0/dma_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
