# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/dma_wrapper.xdc

# Block Designs: bd/dma/dma.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma || ORIG_REF_NAME==dma}]

# IP: bd/dma/ip/dma_processing_system7_0_0/dma_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_processing_system7_0_0 || ORIG_REF_NAME==dma_processing_system7_0_0}]

# IP: bd/dma/ip/dma_axi_dma_0_0/dma_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_axi_dma_0_0 || ORIG_REF_NAME==dma_axi_dma_0_0}]

# IP: bd/dma/ip/dma_axi_mem_intercon_0/dma_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_axi_mem_intercon_0 || ORIG_REF_NAME==dma_axi_mem_intercon_0}]

# IP: bd/dma/ip/dma_rst_ps7_0_100M_0/dma_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_rst_ps7_0_100M_0 || ORIG_REF_NAME==dma_rst_ps7_0_100M_0}]

# IP: bd/dma/ip/dma_axi_gpio_0_0/dma_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_axi_gpio_0_0 || ORIG_REF_NAME==dma_axi_gpio_0_0}]

# IP: bd/dma/ip/dma_xlconcat_0_0/dma_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_xlconcat_0_0 || ORIG_REF_NAME==dma_xlconcat_0_0}]

# IP: bd/dma/ip/dma_ps7_0_axi_periph_0/dma_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_ps7_0_axi_periph_0 || ORIG_REF_NAME==dma_ps7_0_axi_periph_0}]

# IP: bd/dma/ip/dma_xbar_1/dma_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_xbar_1 || ORIG_REF_NAME==dma_xbar_1}]

# IP: bd/dma/ip/dma_axi_gpio_1_0/dma_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_axi_gpio_1_0 || ORIG_REF_NAME==dma_axi_gpio_1_0}]

# IP: bd/dma/ip/dma_I2S_AXI4_0_0/dma_I2S_AXI4_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_I2S_AXI4_0_0 || ORIG_REF_NAME==dma_I2S_AXI4_0_0}]

# IP: bd/dma/ip/dma_xbar_0/dma_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_xbar_0 || ORIG_REF_NAME==dma_xbar_0}]

# IP: bd/dma/ip/dma_auto_pc_0/dma_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_auto_pc_0 || ORIG_REF_NAME==dma_auto_pc_0}]

# IP: bd/dma/ip/dma_auto_us_0/dma_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_auto_us_0 || ORIG_REF_NAME==dma_auto_us_0}]

# IP: bd/dma/ip/dma_auto_us_1/dma_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_auto_us_1 || ORIG_REF_NAME==dma_auto_us_1}]

# IP: bd/dma/ip/dma_s01_mmu_0/dma_s01_mmu_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_s01_mmu_0 || ORIG_REF_NAME==dma_s01_mmu_0}]

# IP: bd/dma/ip/dma_auto_pc_1/dma_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dma_auto_pc_1 || ORIG_REF_NAME==dma_auto_pc_1}]

# XDC: bd/dma/dma_ooc.xdc
