set_property PACKAGE_PIN R18 [get_ports {btn5_tri_i[3]}]
set_property PACKAGE_PIN N15 [get_ports {btn5_tri_i[2]}]
set_property PACKAGE_PIN R16 [get_ports {btn5_tri_i[1]}]
set_property PACKAGE_PIN P16 [get_ports {btn5_tri_i[0]}]
set_property IOSTANDARD LVCMOS15 [get_ports {leds8_tri_o[7]}]
set_property IOSTANDARD LVCMOS15 [get_ports {leds8_tri_o[6]}]
set_property IOSTANDARD LVCMOS15 [get_ports {leds8_tri_o[5]}]
set_property IOSTANDARD LVCMOS15 [get_ports {leds8_tri_o[4]}]
set_property IOSTANDARD LVCMOS15 [get_ports {leds8_tri_o[3]}]
set_property IOSTANDARD LVCMOS15 [get_ports {leds8_tri_o[2]}]
set_property IOSTANDARD LVCMOS15 [get_ports {leds8_tri_o[1]}]
set_property IOSTANDARD LVCMOS15 [get_ports {leds8_tri_o[0]}]
set_property IOSTANDARD LVCMOS15 [get_ports {btn5_tri_i[3]}]
set_property IOSTANDARD LVCMOS15 [get_ports {btn5_tri_i[2]}]
set_property IOSTANDARD LVCMOS15 [get_ports {btn5_tri_i[1]}]
set_property IOSTANDARD LVCMOS15 [get_ports {btn5_tri_i[0]}]

set_property PACKAGE_PIN T18 [get_ports iis_en_n]
set_property IOSTANDARD LVCMOS15 [get_ports iis_en_n]

set_property PACKAGE_PIN R18 [get_ports axi_resetn]
set_property IOSTANDARD LVCMOS15 [get_ports axi_resetn]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
