# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
set_msg_config -msgmgr_mode ooc_run
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/hard_design/zed_dma/zed_dma.cache/wt [current_project]
set_property parent.project_path E:/hard_design/zed_dma/zed_dma.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths {
  e:/hard_design/ip/project/par/project_iis_ip
  e:/hard_design/ip/project/par/iis_gen_ip
  e:/hard_design/ip/project/par/project_int_ip
} [current_project]
set_property ip_output_repo e:/hard_design/zed_dma/zed_dma.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_ip -quiet E:/hard_design/zed_dma/zed_dma.srcs/sources_1/bd/dma/ip/dma_xbar_1/dma_xbar_1.xci
set_property is_locked true [get_files E:/hard_design/zed_dma/zed_dma.srcs/sources_1/bd/dma/ip/dma_xbar_1/dma_xbar_1.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

set cached_ip [config_ip_cache -export -no_bom -use_project_ipc -dir E:/hard_design/zed_dma/zed_dma.runs/dma_xbar_1_synth_1 -new_name dma_xbar_1 -ip [get_ips dma_xbar_1]]

if { $cached_ip eq {} } {

synth_design -top dma_xbar_1 -part xc7z020clg484-1 -mode out_of_context

#---------------------------------------------------------
# Generate Checkpoint/Stub/Simulation Files For IP Cache
#---------------------------------------------------------
catch {
 write_checkpoint -force -noxdef -rename_prefix dma_xbar_1_ dma_xbar_1.dcp

 set ipCachedFiles {}
 write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ dma_xbar_1_stub.v
 lappend ipCachedFiles dma_xbar_1_stub.v

 write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ dma_xbar_1_stub.vhdl
 lappend ipCachedFiles dma_xbar_1_stub.vhdl

 write_verilog -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ dma_xbar_1_sim_netlist.v
 lappend ipCachedFiles dma_xbar_1_sim_netlist.v

 write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ dma_xbar_1_sim_netlist.vhdl
 lappend ipCachedFiles dma_xbar_1_sim_netlist.vhdl

 config_ip_cache -add -dcp dma_xbar_1.dcp -move_files $ipCachedFiles -use_project_ipc -ip [get_ips dma_xbar_1]
}

rename_ref -prefix_all dma_xbar_1_

write_checkpoint -force -noxdef dma_xbar_1.dcp

catch { report_utilization -file dma_xbar_1_utilization_synth.rpt -pb dma_xbar_1_utilization_synth.pb }

if { [catch {
  file copy -force E:/hard_design/zed_dma/zed_dma.runs/dma_xbar_1_synth_1/dma_xbar_1.dcp E:/hard_design/zed_dma/zed_dma.srcs/sources_1/bd/dma/ip/dma_xbar_1/dma_xbar_1.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub E:/hard_design/zed_dma/zed_dma.srcs/sources_1/bd/dma/ip/dma_xbar_1/dma_xbar_1_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub E:/hard_design/zed_dma/zed_dma.srcs/sources_1/bd/dma/ip/dma_xbar_1/dma_xbar_1_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim E:/hard_design/zed_dma/zed_dma.srcs/sources_1/bd/dma/ip/dma_xbar_1/dma_xbar_1_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim E:/hard_design/zed_dma/zed_dma.srcs/sources_1/bd/dma/ip/dma_xbar_1/dma_xbar_1_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}


} else {


if { [catch {
  file copy -force E:/hard_design/zed_dma/zed_dma.runs/dma_xbar_1_synth_1/dma_xbar_1.dcp E:/hard_design/zed_dma/zed_dma.srcs/sources_1/bd/dma/ip/dma_xbar_1/dma_xbar_1.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  file rename -force E:/hard_design/zed_dma/zed_dma.runs/dma_xbar_1_synth_1/dma_xbar_1_stub.v E:/hard_design/zed_dma/zed_dma.srcs/sources_1/bd/dma/ip/dma_xbar_1/dma_xbar_1_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force E:/hard_design/zed_dma/zed_dma.runs/dma_xbar_1_synth_1/dma_xbar_1_stub.vhdl E:/hard_design/zed_dma/zed_dma.srcs/sources_1/bd/dma/ip/dma_xbar_1/dma_xbar_1_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force E:/hard_design/zed_dma/zed_dma.runs/dma_xbar_1_synth_1/dma_xbar_1_sim_netlist.v E:/hard_design/zed_dma/zed_dma.srcs/sources_1/bd/dma/ip/dma_xbar_1/dma_xbar_1_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  file rename -force E:/hard_design/zed_dma/zed_dma.runs/dma_xbar_1_synth_1/dma_xbar_1_sim_netlist.vhdl E:/hard_design/zed_dma/zed_dma.srcs/sources_1/bd/dma/ip/dma_xbar_1/dma_xbar_1_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

}; # end if cached_ip 

if {[file isdir E:/hard_design/zed_dma/zed_dma.ip_user_files/ip/dma_xbar_1]} {
  catch { 
    file copy -force E:/hard_design/zed_dma/zed_dma.srcs/sources_1/bd/dma/ip/dma_xbar_1/dma_xbar_1_stub.v E:/hard_design/zed_dma/zed_dma.ip_user_files/ip/dma_xbar_1
  }
}

if {[file isdir E:/hard_design/zed_dma/zed_dma.ip_user_files/ip/dma_xbar_1]} {
  catch { 
    file copy -force E:/hard_design/zed_dma/zed_dma.srcs/sources_1/bd/dma/ip/dma_xbar_1/dma_xbar_1_stub.vhdl E:/hard_design/zed_dma/zed_dma.ip_user_files/ip/dma_xbar_1
  }
}
