# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/hard_design/zed_dma/zed_dma.srcs/sources_1/bd/dma/ip/dma_axi_gpio_0_0/dma_axi_gpio_0_0.xci
# IP: The module: 'dma_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/hard_design/zed_dma/zed_dma.srcs/sources_1/bd/dma/ip/dma_axi_gpio_0_0/dma_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: e:/hard_design/zed_dma/zed_dma.srcs/sources_1/bd/dma/ip/dma_axi_gpio_0_0/dma_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: e:/hard_design/zed_dma/zed_dma.srcs/sources_1/bd/dma/ip/dma_axi_gpio_0_0/dma_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: E:/hard_design/zed_dma/zed_dma.srcs/sources_1/bd/dma/ip/dma_axi_gpio_0_0/dma_axi_gpio_0_0.xci
# IP: The module: 'dma_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/hard_design/zed_dma/zed_dma.srcs/sources_1/bd/dma/ip/dma_axi_gpio_0_0/dma_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: e:/hard_design/zed_dma/zed_dma.srcs/sources_1/bd/dma/ip/dma_axi_gpio_0_0/dma_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: e:/hard_design/zed_dma/zed_dma.srcs/sources_1/bd/dma/ip/dma_axi_gpio_0_0/dma_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
